server: 
  port: 8085

spring:
  servlet:
     multipart:
       enabled: true
       max-file-size: 100MB
       max-request-size: 100MB  
       file-size-threshold: 1KB
                
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    
  jpa: 
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      
      